### ISSUE TITLE
Check consistency between merge target and title.

### ISSUE THREAD

**Issue by terryjreedy** [python/bedevere#111] opened 2018-06-24 01:58 UTC
https://github.com/python/cpython/pull/7765
is a trivial doc change intended for master, 3.7, 3.6, and 2.7.  I reviewed,
approved, marked labels, and after a 2nd approval, merged it. miss-islington
cherry-picked it to 3.7, but failed for 3.6 and 2.7.  The author then discovered
that the 3.6 failure was because the original PR was (accidentally) against
3.6, not master.

On core_mentorship, Nick suggested that the best way to catch such an error is for Bedevere to check consistency between between branch merge target (in above case, 3.6) and the presence or absence of a branch label (in above case, none). 

"When bedevere checks for the BPO issue reference, it could also check
that the target branch matches the commit message prefix (i.e. if
there's no "[3.6] " at the start, then targetting the 3.6 branch is
wrong - PRs without a version prefix should always be targeting
master, and PRs deliberately targeting a maintenance branch directly
should include the prefix).
"
Possible message: 
"If this PR is really for 3.6, prefix [3.6] to the title.
If this PR is for master, CLOSE IT and make a new PR."

**Comment by Mariatta** [comment] 2018-06-24 02:07
Duplicate of https://github.com/python/core-workflow/issues/211

**Closed** 2018-07-21 03:44 UTC
