### ISSUE TITLE
Bedevere rejects change that targets another PR

### ISSUE THREAD

**Issue by jaraco** [python/bedevere#381] opened 2021-12-16 19:47 UTC
In https://github.com/python/cpython/pull/30151, I've written a PR that's based on another PR. In order for the diff to look right but for the code to be based on another PR, I've set the target for the PR as the other PR:

![image](https://user-images.githubusercontent.com/308610/146437948-7fc866f2-a972-4b03-a670-ffa1eba42988.png)

Github supports this workflow and even has some nice features around it. In particular, when https://github.com/python/cpython/pull/30150 is merged, Github will automatically detect the merge and will re-point the 30151 to point to `main`.

Unfortunately, this workflow trips up on bedevere's check for maintenance branch PR naming, causing the tests not to run:

![image](https://user-images.githubusercontent.com/308610/146438290-d00f0ac2-24dc-41ff-bf6a-57fb51f828d1.png)

It would be nice if bedevere would not enforce the naming check if it's not pointing at a maintenance branch. Even better would be for it to recognize that it's pointing at a branch that's pending merge to `main` or a maintenance branch and use that resolution to make its check.

Impact due to this issue is small, and I'm not even sure there's enough value in fixing the issue, but I'd like to register it regardless.

**Comment by jaraco** [comment] 2021-12-16 19:53
For this particular case, I found I was able to actually rebase the dependent change, making it independent, and target it at main separately, working around the issue. This would not have been possible if there had been a hard dependency on the first PR.

**Comment by arhadthedev** [comment] 2022-06-19 07:44
Is the issue relevant after the migration?

**Comment by ezio-melotti** [comment] 2022-06-19 07:52
Since the issue seems to be about PRs based on other PRs, the migration doesn't affect this issue.  We should verify if the issue is still present or if it got fixed in the meanwhile before closing this.

**Closed** 2022-06-20 19:08 UTC

**Comment by jaraco** [comment] 2022-07-03 15:00
I wanted to confirm, this change appears to be working, as is evidenced by https://github.com/python/cpython/pull/94528, which targets https://github.com/python/cpython/pull/93965.

**Comment by Mariatta** [comment] 2022-07-03 17:12
Awesome. Thank you!
