### ISSUE TITLE
Incorrect bedevere transition

### ISSUE THREAD

**Issue by hauntsaninja** [python/bedevere#558] opened 2023-05-08 03:41 UTC
I'm not quite sure what happened on https://github.com/python/cpython/pull/104281 but it should have ended up in "awaiting merge" state instead of "awaiting core review":

<img width="878" alt="Screenshot 2023-05-07 at 8 41 19 PM" src="https://user-images.githubusercontent.com/12621235/236728784-35752ea0-db04-4624-b05e-2c0b3e638c88.png">

**Comment by arhadthedev** [comment] 2023-05-08 04:14
Related to gh-556 (or a duplicate of, have no experience with GitHub API to determine).

**Closed** 2023-05-10 16:48 UTC
