### ISSUE TITLE
Is Bedevere retired?

### ISSUE THREAD

**Issue by skirpichev** [python/bedevere#604] opened 2023-11-03 10:00 UTC
I was thinking he doesn't like just me, after several comments in https://github.com/python/cpython/pull/111418 (e.g. https://github.com/python/cpython/pull/111418#issuecomment-1786556359, https://github.com/python/cpython/pull/111418#issuecomment-1791856791 and https://github.com/python/cpython/pull/111418#issuecomment-1791857093) - the pr is still labeled as "awaiting changes".

But he doesn't like others too:
* https://github.com/python/cpython/pull/111648
* https://github.com/python/cpython/pull/111322

Dark times coming?

**Comment by AlexWaygood** [comment] 2023-11-03 10:02
duplicate of #599

**Closed by AlexWaygood** 2023-11-03 10:02 UTC

**Comment by skirpichev** [comment] 2023-11-03 10:05
Oops, sorry :(  I was misguided by title of that issue.
